### ISSUE TITLE
Rebinding UnionOfRows affects other packages.

### ISSUE THREAD

**Issue by kamalsaleh** [MWhybrow92/MajoranaAlgebras#45]
https://github.com/MWhybrow92/MajoranaAlgebras/blob/4059e74c61d6aefbd993fcf09b1922c95998d232/gap/LinAlg.gi#L7-L13

The above code interferes with operations in other packages and causes unexpected behaviors when using the operation `UnionOfRows`, for example as in https://github.com/homalg-project/NConvex/issues/5. The tests in `MajoranaAlgebras` still pass without this change, so I think it is not necessary with the current versions of `Gaus`.

If it is indeed still necessary, I would suggest making it an operation which makes some tests on the arguments and if these tests return `false`, then simply `TryNextMethod()`.

Best wishes

**Comment by olexandr-konovalov** [comment]
@MWhybrow92 can we just delete this as @kamalsaleh suggests?

**Comment by olexandr-konovalov** [comment]
@kamalsaleh noticed that this was closed without any changes in this package - was it resolved elsewhere?

**Comment by kamalsaleh** [comment]
No, not yet. I don't think this can be resolved elsewhere :)

**Comment by fingolfin** [comment]
That's indeed a BAD hack that needs to go. Without knowing what it is/was used for, it's non-trivial to suggest an appropriate fix. Presumably the problem (whatever it is/was?) was fixed in Gauss at some point; in that case it should be sufficient to set a corresponding minimal version for Gauss in the dependency list.

Or perhaps the issue is not yet fixed -- then it'd be good to know about it, get it fixed, and then remove the hack here and add the versioned Gauss dependency...

**Comment by fingolfin** [comment]
Actually, Gauss doesn't even define `UnionOfRows`, so the code comment is misleading -- perhaps Gauss used to define it? It now defines `SparseUnionOfRows`. 

Anyway, another option would be to rename `UnionOfRows` here to `MAJORANA_UnionOfRows`. I don't know the code well enough to judge this

**Comment by olexandr-konovalov** [comment]
Need to check if @markuspf and @MWhybrow92 are still maintainers as said in `PackageInfo.g`...
